ifdef::backend-manpage[]
= rearr(1)
:doctype: manpage
:man manual: User commands
:man source: rearrange-columns {release-version}
:page-layout: base
:command: rearr

endif::[]
== NAME

rearr - Rearrange sections in each lines of files

== SYNOPSIS

*rearr* [_OPTION_] [_FILE_]

== DESCRIPTION

*rearr* is a small utility to rearrange sections in each line of files.

It can remove and duplicate sections and also change the order of sections.

With no FILE, or when FILE is `-`, read standard input.

== OPTIONS

// tag::options[]
*-h*::
Display help.

*-d* _DELIM_::
Use DELIM instead of TAB for field delimiter.

*-o* _DELIM_::
Use DELIM as the output delimiter the default is to use the input delimiter.

*-f* _LIST_::
Select only these fields;  also print any line that contains no delimiter character, unless the -s option is specified.
Each item of the list is a number (=1 for the first, -1 for the last) or a range (start:end where values are includes)

*-c* _LIST_::
select only these characters.
Each item of the list is a number (=1 for the first, -1 for the last) or a range (start:end where values are includes)


== EXAMPLES
// tag::examples[]
.Display fields 4, 1 to 3 and the 2 lasts of `/etc/passwd` changing the output separator to `;`.
[source,shell]
----
$ rearr -f4,1:3,-2: -d: -o';' /etc/passwd | head
0;root;x;0;/root;/bin/bash
1;daemon;x;1;/usr/sbin;/usr/sbin/nologin
2;bin;x;2;/bin;/usr/sbin/nologin
3;sys;x;3;/dev;/usr/sbin/nologin
65534;sync;x;4;/bin;/bin/sync
60;games;x;5;/usr/games;/usr/sbin/nologin
12;man;x;6;/var/cache/man;/usr/sbin/nologin
7;lp;x;7;/var/spool/lpd;/usr/sbin/nologin
8;mail;x;8;/var/mail;/usr/sbin/nologin
9;news;x;9;/var/spool/news;/usr/sbin/nologin
----
// end::examples[]

ifdef::backend-manpage[]
include::author.adoc[]
include::copyright.adoc[]
endif::[]